config/routes.rb
GroupsOfLists::Application.routes.draw do
  get "groups/show"

  resources :tasks

  resources :groups do
    resources :tasks
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :tasks

  validates_presence_of :name
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_and_belongs_to_many :groups

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find params[:id]
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find params[:id]
  end

  def new
    @group = Group.find(params[:group_id]) if params[:group_id]
    @task = Task.new
  end

  def create
    task = Task.new params[:task]
    task.groups << Group.find(params[:group_id]) if params[:group_id]

    if task.save
      redirect_to task
    else
      render :action => "new"
    end
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    task = Task.find params[:id]

    if task.update_attributes params[:task]
      redirect_to task
    else
      render :action => "edit"
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<%= link_to "New task", new_group_task_path(@group) %>

<% if @group.tasks.present? %>
  <ul>
    <% for task in @group.tasks %>
      <li><%= link_to task.name, task %></li>
    <% end %>
  </ul>
<% else %>
  <p>No tasks for this group</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupsOfLists</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.name %></h1>

<%= form_for @task do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= link_to "New task", new_task_path %>

<% if @tasks.present? %>
  <ul>
    <% for task in @tasks %>
      <li><%= link_to task.name, task %></li>
    <% end %>
  </ul>
<% else %>
  <p>No tasks for this group</p>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for [@group, @task] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>

<%= @task.description %>

<% if @task.groups.present? %>
  <h2>Groups</h2>

  <ul>
    <% for group in @task.groups %>
      <li><%= link_to group.name, group %></li>
    <% end %>
  </ul>
<% end %>

<p><%= link_to "All tasks", tasks_path %></p>

<%= form_for @task, :method => "delete" do |f| %>
  <p><%= f.submit "Delete" %></p>
<% end %>